# Branch protection configuration for main
# This file documents the required checks to be configured in the GitHub UI or via API
# Apply to branch: main

required_status_checks:
  strict: true
  contexts:
    - "CI (build-test)"
    - "CodeQL / Analyze"
    - "codecov/project"
    - "codecov/patch"

required_pull_request_reviews:
  required_approving_review_count: 1
  dismiss_stale_reviews: true
  require_code_owner_reviews: false

enforce_admins: true

restrictions: null
