# Central label catalog for this repository
# Syncs via .github/workflows/sync-labels.yml
# Format: list of labels with name, color (hex w/o #), and description

- name: "type:feature"
  color: "a2eeef"
  description: "New feature or enhancement"
- name: "type:bug"
  color: "d73a4a"
  description: "Something isn't working (bug)"
- name: "type:docs"
  color: "0075ca"
  description: "Documentation-only changes"
- name: "type:chore"
  color: "d4c5f9"
  description: "Repo maintenance or chores"
- name: "type:test"
  color: "e4e669"
  description: "Adding or updating tests"
- name: "type:refactor"
  color: "cfd3d7"
  description: "Code refactoring with no behavior change"
- name: "type:ci"
  color: "5319e7"
  description: "Continuous Integration / workflow changes"

# Scopes (path-based areas of the repo)
- name: "scope:contracts"
  color: "1d76db"
  description: "Packages: contracts"
- name: "scope:core"
  color: "1d76db"
  description: "Core runtime and shared infrastructure"
- name: "scope:agents"
  color: "1d76db"
  description: "Source: agents"
- name: "scope:skills"
  color: "1d76db"
  description: "Source: skills"
- name: "scope:channels"
  color: "1d76db"
  description: "Source: channels"
- name: "scope:apps"
  color: "1d76db"
  description: "Applications under /apps"
- name: "scope:docs"
  color: "1d76db"
  description: "Documentation under /docs and top-level README"
- name: "scope:tests"
  color: "1d76db"
  description: "Tests under /tests"
- name: "scope:examples"
  color: "1d76db"
  description: "Examples under /examples"
- name: "scope:templates"
  color: "1d76db"
  description: "Project templates under /templates"
- name: "scope:scripts"
  color: "1d76db"
  description: "Automation and helper scripts"
- name: "scope:ci"
  color: "1d76db"
  description: "CI workflows under .github/workflows"
- name: "scope:repo"
  color: "1d76db"
  description: "Repository meta and configuration"

# Semantic versioning impact
- name: "semver:major"
  color: "b60205"
  description: "Breaking change (requires major version bump)"
- name: "semver:minor"
  color: "d93f0b"
  description: "Backward-compatible feature (minor version bump)"
- name: "semver:patch"
  color: "0e8a16"
  description: "Backward-compatible bug fix (patch version bump)"

# Workflow/status labels
- name: "status:ready"
  color: "0e8a16"
  description: "Ready for review / merge"
- name: "status:in-progress"
  color: "0075ca"
  description: "Work in progress"
- name: "status:blocked"
  color: "b60205"
  description: "Blocked or awaiting dependency"
- name: "status:needs-info"
  color: "fbca04"
  description: "Needs more information"

# Priority labels
- name: "priority:P0"
  color: "b60205"
  description: "Highest priority"
- name: "priority:P1"
  color: "d93f0b"
  description: "High priority"
- name: "priority:P2"
  color: "fbca04"
  description: "Medium priority"
- name: "priority:P3"
  color: "0e8a16"
  description: "Low priority"

# Size labels (applied automatically by size-label workflow)
- name: "size:XS"
  color: "ededed"
  description: "Up to 10 LOC changed"
- name: "size:S"
  color: "bfdadc"
  description: "11–50 LOC changed"
- name: "size:M"
  color: "c5def5"
  description: "51–200 LOC changed"
- name: "size:L"
  color: "c2e0c6"
  description: "201–500 LOC changed"
- name: "size:XL"
  color: "f9d0c4"
  description: ">500 LOC changed"
