# Codecov configuration for X-Skynet
# Docs: https://docs.codecov.com/docs/codecovyml-reference

# Do not post a PR comment; rely on GitHub Checks instead
comment: false

coverage:
  status:
    project:
      default:
        # Keep current overall coverage from regressing too much
        target: auto
        threshold: 2%
      # Example per-flag project gate scoped to CI flag 'node-20.x'
      node-20:
        flags: ["node-20.x"]
        target: auto
        threshold: 2%
    patch:
      default:
        # Require reasonable coverage on changed lines in PRs
        target: 80%
        threshold: 1%
        only_pulls: true
      # Example per-flag patch gate scoped to CI flag 'node-20.x'
      node-20:
        flags: ["node-20.x"]
        target: 80%
        threshold: 1%
        only_pulls: true

# Carry forward previous flag results when some flags are missing in a run
# (useful with matrix builds)
flag_management:
  default_rules:
    carryforward: true
  # Explicit example flag so it shows up in the Flags dashboard
  individual_flags:
    - name: "node-20.x"
      carryforward: true

# Define per-package Components so each package has its own coverage status checks
# See: https://docs.codecov.com/docs/components
component_management:
  # Default status rules applied to all components (can be overridden per-component)
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 2%
      - type: patch
        target: 80%
        threshold: 1%
        only_pulls: true
  # Individual package components (monorepo)
  individual_components:
    - component_id: pkg-cli
      name: "pkg:cli"
      paths:
        - "packages/cli/**"
    - component_id: pkg-contracts
      name: "pkg:contracts"
      paths:
        - "packages/contracts/**"
    - component_id: pkg-core
      name: "pkg:core"
      paths:
        - "packages/core/**"
    - component_id: pkg-memory
      name: "pkg:memory"
      paths:
        - "packages/memory/**"
    - component_id: pkg-mission-control
      name: "pkg:mission-control"
      paths:
        - "packages/mission-control/**"
    - component_id: pkg-plugin-claude
      name: "pkg:plugin-claude"
      paths:
        - "packages/plugin-claude/**"
    - component_id: pkg-plugin-http
      name: "pkg:plugin-http"
      paths:
        - "packages/plugin-http/**"
    - component_id: pkg-plugin-shell
      name: "pkg:plugin-shell"
      paths:
        - "packages/plugin-shell/**"
    - component_id: pkg-sdk-js
      name: "pkg:sdk-js"
      paths:
        - "packages/sdk-js/**"
    - component_id: pkg-viewer
      name: "pkg:viewer"
      paths:
        - "packages/viewer/**"
