coverage:
  status:
    project:
      default:
        # Require overall project coverage to meet target; allow small fluctuations
        target: 80%
        threshold: 1%
    patch:
      default:
        # New/changed lines must be well-covered
        target: 90%
        threshold: 0%

# Reduce noise from unrelated deletions
comment:
  layout: "reach,diff,flags,files"
  require_changes: true
  require_base: false
  require_head: true

# Component-based coverage gates per major package
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
        threshold: 0%
  individual_components:
    - component_id: core
      name: core
      paths:
        - packages/core/**
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - component_id: cli
      name: cli
      paths:
        - packages/cli/**
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - component_id: sdk-js
      name: sdk-js
      paths:
        - packages/sdk-js/**
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - component_id: contracts
      name: contracts
      paths:
        - packages/contracts/**
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - component_id: router
      name: router
      paths:
        - packages/router/**
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - component_id: web-ui
      name: web-ui
      paths:
        - packages/web-ui/**
      statuses:
        - type: project
          target: auto
          threshold: 1%
    - component_id: plugins
      name: plugins
      paths:
        - packages/plugin-*/**
      statuses:
        - type: project
          target: auto
          threshold: 1%

# Keep GitHub Checks annotation noise low
github_checks:
  annotations: false
